### ISSUE TITLE
ros with stm32cubeIDE

### ISSUE THREAD

**Issue by Theara-Seng** [xav-jann1/rosserial_stm32f4#1]
when I use the command  rosrun rosserial_python serial_node.py /dev/ttyACM0 I get the following error. can you help me 
![Uploading Screenshot from 2019-12-08 20-50-54.png…]()

**Comment by xav-jann1** [comment]
The image is not working...

Could you send it again, or simply put the text of the error in a new message ?

**Comment by Theara-Seng** [comment]
[INFO] [1581992396.350275]: ROS Serial Python Node
[INFO] [1581992396.357997]: Connecting to /dev/ttyACM0 at 57600 baud
[INFO] [1581992398.463643]: Requesting topics...
[ERROR] [1581992413.466078]: Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino

I get this following error.

**Comment by Theara-Seng** [comment]
I see in your example, do I just add some function to the main.c of the Core of my project ?

**Comment by xav-jann1** [comment]
This error happens when *ROS* cannot communicate with the microcontroller. It could be because *ROS* is not running on it or because the *baud rate* is wrong.

So, yes, you should follow the steps in the [example README](https://github.com/xav-jann1/rosserial_stm32f4/blob/master/example/README.md), where you have to create [`mainpp.h`](https://github.com/xav-jann1/rosserial_stm32f4/blob/master/example/mainpp.h) and [`mainpp.cpp`](https://github.com/xav-jann1/rosserial_stm32f4/blob/master/example/mainpp.cpp) files ; and also include a file (`mainpp.cpp`), and add `setup()` and `loop()` functions in your `main.c` in `Core/Src` folder.

Also, you should have followed the steps in the [repository README](https://github.com/xav-jann1/rosserial_stm32f4/blob/master/README.md#usage), to create a project with *STM32CubeIDE* and add `ros_lib` to it, thanks to this package.

Finally, check the *baud rate* used by your microcontroller in its configuration. Generally, by default it is `115 200 baud/s`, so you should use the command below to run `rosserial_python` with the correct *baud rate* :
```sh
$ rosrun rosserial_python serial_node.py _port:=/dev/ttyACM0 _baud:=115200
```

**Comment by Theara-Seng** [comment]
I still get the same error even if I change the baud rate to 115200 baud/s. It works fine with Arduino IDE. I can subscribe and publish with Arduino mega. I use the stm32f303VCTX and I change to the 4 to 3 as in the readme. I see in the rosserial_arduino and rosserial_python. There is a serial_node.py which in the code there is a baud and port, but in the STM32, I can't find one. One more thing is that when ctr_C in the error I see a script "attempting to use a port that is not open"

**Comment by xav-jann1** [comment]
You can find the *baud rate* in the `main.c` file, in the `MX_USART2_UART_Init()` function :
```c
/**
  * @brief USART2 Initialization Function
  * @param None
  * @retval None
  */
static void MX_USART2_UART_Init(void)
{
  ...
  huart2.Instance = USART2;
  huart2.Init.BaudRate = 38400;
  ...
}
```

It can also be found in the *configuration file* of your project : `project_name.ioc`.
Double click on this file to open a *UI* that lets you configure the microcontroller and automatically generate the code.
On the left panel, go to `Connectivity`, then `USART2`, and in `Parameter Settings`, you should find the *baud rate*.
(Also, it's with this interface that you should have configured `Global Interrupt` and `DMA` for the *USART*).

Maybe, it will work with `38400 baud/s`.

**Comment by xav-jann1** [comment]
Also, you should first test if the *UART* is working without `rosserial`.

To test it, you should remove the calls to the `setup()` and `loop()` functions in the `main()` function in `main.c`, and use the following code in the `while` loop :
```c
  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
    uint8_t text[] = "Hello\n\r";
    HAL_UART_Transmit(&huart2, (uint8_t *)text, 7, 0xFFFF);
    HAL_Delay(1000);
  }
  /* USER CODE END 3 */
```
This code send every second `Hello`.

Flash it to your microcontroller.

Then, find what *interface* your card is using to connect to your computer, with this command :
(connect the *USB* to your computer, then execute the command)
```sh
$ dmesg | grep tty
```

You should find an *id* starting with `tty`.

Finally, connect to the *serial interface* with the correct *baud rate* to see the messages :
```sh
$ screen /dev/ttyACM0 38400
```

To quit the screen, `CTRL+A`, then `k`, then `y`.

If you can see `Hello` messages, then you know how to communicate with your microcontroller.

---
If you cannot access the *interface* with `screen` to display the messages, try the command with `sudo` or add the `dialout` group to your groups :
```sh
# List your groups:
$ groups ${USER}

# Add 'dialout' group to your groups:
$ sudo gpasswd --add ${USER} dialout
```

**Comment by xav-jann1** [comment]
Finally, to be certain it will work with the `rosserial` implementation, you should also try to send messages with `DMA`, by using this code for the `while` loop :
```c
  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
    uint8_t text[] = "Hello\n\r";
    HAL_UART_Transmit_DMA(&huart2, (uint8_t *)text, 7);
    HAL_Delay(1000);
  }
  /* USER CODE END 3 */
```
If there is no message, check that `DMA` and `Global Interrupt` for *USART2* are correctly configured.

And if you can see messages, then you can test with `rosserial`.

**Comment by Theara-Seng** [comment]
Thank you @xav-jann1 for your help so far. It works now.
