### ISSUE TITLE
The code is not being compiled because of some errors in the BufferedSerial.cpp File

### ISSUE THREAD

**Issue by Abo3abed** [xav-jann1/rosserial_stm32f4#2]
I'm getting the following error: 
`../Core/Src/BufferedSerial.cpp:17:5: error: class 'BufferedSerial' does not have any field named 'huart'`
and:
`../Core/Src/BufferedSerial.cpp:16:1: error: uninitialized reference member in 'UART_HandleTypeDef& {aka struct __UART_HandleTypeDef&}' [-fpermissive]
`
can you please tell what to do in this case ?

**Comment by xav-jann1** [comment]
I tested again the example, and had no problem with compiling it.

Did you follow the [*Usage*](https://github.com/xav-jann1/rosserial_stm32f4#usage) section and the [*example*](https://github.com/xav-jann1/rosserial_stm32f4/tree/master/example#simple-example) ? 
Also, on what microcontroller do you program for ?

**Comment by Abo3abed** [comment]
I did what in the usage and the example step by step and this error showed up, I'm using stm32f767 and I made sure to change that in the files. 

Firstly, I had to change every huart in BufferedSerial.cpp to the huart handler I'm using (i.e. huart1).

I have no idea why that error regarding huart is not a member is showing! 
Note: I'm using ros-melodic but I think this shouldn't be the issue, no ?

**Comment by xav-jann1** [comment]
To work with another `huart?`, you only need to change the values in `BufferedSerial.cpp` in those two lines :
```cpp
extern UART_HandleTypeDef huart?;

// Create Serial Buffer with UART?:
BufferedSerial buff_serial(huart?);
```

**Comment by xav-jann1** [comment]
Also, I tested for the MCU `STM32F767BG`, and it compiled correctly.

For the example to work, I just had to change *includes* from `f4` to `f7` in `BufferedSerial.hpp`, and also to add `USART2` and choose `Asynchronous`.

Here is the project I tested with : [test_f7.zip](https://github.com/xav-jann1/rosserial_stm32f4/files/4443809/test_f7.zip).
You can unzip and import it in *STM32CubeIDE* and test by yourself if it works on your system.

*Note* : I'm also using `ROS Melodic` on *Windows* with *WSL*.

**Comment by Abo3abed** [comment]
the code got compiled after the changes, it was me missing up with huart, thanks a lot.

However, when I run rosserial_python it gives me this error:

```
rosrun rosserial_python serial_node.py _port:=/dev/ttyACM0 _baud:=115200

[INFO] [1586261043.273145]: ROS Serial Python Node

[INFO] [1586261043.284883]: Connecting to /dev/ttyACM0 at 115200 baud

[INFO] [1586261045.392277]: Requesting topics...

[ERROR] [1586261060.396457]: Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino
```

I used your code to double check! 
I would appreciate it if you can help

**Comment by xav-jann1** [comment]
Are you sure your microcontroller is connected through `/dev/ttyACM0` ?

You should first test if the *UART* is working without `rosserial`.

To test it, remove the calls to the `setup()` and `loop()` functions in the `main()`  in `main.c`, and use the following code in the `while` loop, with the correct `huart?` in `HAL_UART_Transmit()` :
```c
  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
    uint8_t text[] = "Hello\n\r";
    HAL_UART_Transmit(&huart?, (uint8_t *)text, 7, 0xFFFF);
    HAL_Delay(1000);
  }
  /* USER CODE END 3 */
```
This code sends every second `Hello`.

**Comment by Abo3abed** [comment]
I used minicom and configured it to the same port settings and nothing is coming out! 
how can I fix it ?

Does it have anything to do with debugging configuration ? as JTAG and SWD things?

**Comment by xav-jann1** [comment]
I don't think it caused by *JTAG* or *SWD*.

Did you select the correct pins on the *microcontroller* to connect the `UART` *Tx* and *Rx* pins to your *UART to USB controller* (like *ST-Link*) that connects to your *PC* ?

---
Also, you can find what *interface* your card is using to connect to your computer, with this command :
(connect the *USB* to your computer, then execute the command)
```sh
$ dmesg | grep tty
```

**Comment by Abo3abed** [comment]
Well, I got it to work with minicom, and now it is printing the Hello statement, however, rosserial_python still gives the same error?

**Comment by Abo3abed** [comment]
Thanks a lot for your help, I had to edit the port according to the schematic and restart the terminal for changes to take effect! 
I appreciate your time!
