### ISSUE TITLE
[ERROR] [1675865339.459133]: Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino

### ISSUE THREAD

**Issue by emredaglier** [xav-jann1/rosserial_stm32f4#3]
Unfortunately i couldn't make my STM32F407 up and running for ROS Melodic on 18.04

```
rosrun rosserial_python serial_node.py /dev/ttyACM0 _baud:=115200
[INFO] [1675864286.784820]: ROS Serial Python Node
[INFO] [1675864286.799455]: Connecting to /dev/ttyACM0 at 115200 baud
[INFO] [1675864288.908526]: Requesting topics...
[ERROR] [1675864303.918928]: Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino
```
I've set my USART2 mode to Asynchronous and set it to Global Interrupt in NVIC settings. Created USART2_RX and TX and set their priority to High. I left the baud rate at 115200 but also tried 56700 and 38400. My project is running on C++ and there's no problem uploading the code to the controller.
Also I've connected my STM32F407 to my laptop using a Mini USB B cable and nothing more. No problem about finding and giving the permission to the right port to receive data.
Besides rosserial not being working, i also couldn't publish data using HAL_UART_Transmit() and HAL_UART_Transmit_DMA() leading that means UART isn't working properly I guess. I've also tried to used UART3 just in case but no luck at all.

Also this is my workspace that I'm having issues on:
[stmros.zip](https://github.com/xav-jann1/rosserial_stm32f4/files/10686498/stmros.zip)

I'd be glad to see where I'm doing wrong or missed.
Thanks!

**Comment by xav-jann1** [comment]
Hello,

Before trying to use _rosserial_, you should first try to run a very simple program that blinks a LED and sends text with _USART_.

From the workspace you sent, you use the development board [`STM32F407G-DISC1`](https://www.st.com/en/evaluation-tools/stm32f4discovery.html).
In the [_User Manual_ of this development board](https://www.st.com/resource/en/user_manual/um1472-discovery-kit-with-stm32f407vg-mcu-stmicroelectronics.pdf), there is a part about _USART_ (page 15) :
> The ST-LINK/V2-A supports a Virtual COM port (VCP) on U2 pin 12 (ST-LINK_TX) and U2
> pin 13 (ST-LINK_RX) but these pins are not connected to the USART of the STM32F407
> microcontroller.
> Two solutions are possible to connect an STM32F407 USART to the VCP on the PC:
> - Using an USART to USB dongle from the market connected for instance to
> STM32F407 USART2 available on connector P1 pin 14 (PA2: USART2_TX) and P1
> pin 13 (PA3: USART2_RX).
> - Using flying wires to connect ST-LINK/V2-A Virtual COM port (ST-LINK VCP on U2 pin
> 12 and 13) to STM32F407 USART2 (PA2 and PA3: P1 pin 14 and 13) as shown in
> Figure 6

So, on this board, no _USART_ of the MCU is connected to _ST-Link_.

Then, it seems that you need a _USB to Serial_ adapter to connect your PC to a _USART_ of the board (for example _USART2_ from pins _PA2_ and _PA3_).
Also, do not forget to share ground between the board and the adapter.

**Comment by emredaglier** [comment]
Many thanks for this, I'll order a USB-TTL dongle as soon as possible. Unfortunately I'm new to STM series and it's being complicated sometimes for a rookie. I'll create an Issue again if I encounter another problem about USART. I won't leave this case open just to not make a mess.

Thank you for your time.
Cheers
